Table Output Helper + Ping Command
remove writer / cleanup defs

Add missing deps

Started some testing + abstract out the writer used for output

Missing deps

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -2,4 +2,16 @@
 set -e
 cd $(dirname "$0")/..
 
-go test -v ./...
+FMT_ERRS=$(gofmt -l . 2>&1 | tee /dev/tty | wc -l)
+if [ "$FMT_ERRS" -gt "0" ]; then
+  echo "$FMT_ERRS Lint error(s) found in above file(s)."
+  exit 1
+fi
+
+VET_ERRS=$(go tool vet -test . 2>&1 | tee /dev/tty | wc -l)
+if [ "$VET_ERRS" -gt "0" ]; then
+   echo "$VET_ERRS Vet error(s) found above."
+  exit 1
+fi
+
+go test -cover ./...
